In [1]:
%pip install xlrd openpyxl

Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [2]:
import pandas as pd

In [8]:
# Read data from CSV file

# csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv'
# df = pd.read_csv(csv_path)

# from pyodide.http import pyfetch


# filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"

# async def download(url, filename):
#     response = await pyfetch(url)
#     if response.status == 200:
#         with open(filename, "wb") as f:
#             f.write(await response.bytes())


# await download(filename, "Product-sales.csv")
# df = pd.read_csv("Product-sales.csv")

import pandas as pd

# 1. Define the correct, direct cloud storage path
csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv'

try:
    # 2. Read the remote CSV directly into a DataFrame
    df = pd.read_csv(csv_path)

    # 3. Show the first 5 rows of your data
    print("✅ Data loaded successfully!")
    display(df.head())

except Exception as e:
    print(f"❌ Error loading data: {e}")

✅ Data loaded successfully!

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [18]:
import os
import urllib.request
import pandas as pd

# 1. Exact IBM Cloud storage link to your product sales data
csv_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"
local_filename = "Product-sales.csv"

print(f"📡 Requesting download from: {csv_url}")

async def download(url, filename):
    try:
        # 2. Safely download and write the file locally
        urllib.request.urlretrieve(url, local_filename)
        print("✅ File successfully downloaded!")

        # 3. Read and display the CSV dataset
        # df = pd.read_csv(local_filename)
        # display(df.head())

    except Exception as e:
        print(f"❌ Download failed: {e}")

await download(csv_url, local_filename)

# 3. Read the downloaded target file
if os.path.exists(local_filename):
    df = pd.read_csv(local_filename)
    display(df.head())

📡 Requesting download from: https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv
✅ File successfully downloaded!

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [21]:
xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n9LOuKI9SlUa1b5zkaCMeg/Product-sales.xlsx'
local_filename = "Product-sales.xlsx"

await download(xlsx_path, local_filename)
if os.path.exists(local_filename):
    df = pd.read_excel(local_filename)
    display(df.head())

✅ File successfully downloaded!

/usr/local/lib/python3.13/dist-packages/openpyxl/chart/__init__.py:5: RuntimeWarning: coroutine 'download_async' was never awaited
  from .bubble_chart import BubbleChart
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [23]:
q = df[['Price']]
q

   Price
0    800
1    600
2    150
3      2
4    300

In [25]:
q = df[['Product','Category']]
q

      Product     Category
0      Laptop  Electronics
1  Smartphone  Electronics
2  Desk Chair    Furniture
3    Notebook   Stationery
4     Monitor  Electronics

In [29]:
x = df.iloc[1,2]
x

'Electronics'

In [31]:
new_index=['a','b','c','d','e']
df_new = df.set_index([new_index])
df_new

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
a,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
b,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
c,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
d,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
e,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [34]:
el = df_new.loc['a' , 'CustomerCity']
el

'New York'

In [33]:
f = df_new.loc['a':'d' , 'CustomerCity']
f

a       New York
b    Los Angeles
c        Chicago
d        Houston
Name: CustomerCity, dtype: object