In [3]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [9]:
student = {
    "Name" : ['David' , "Samuel"  ,"Terry" , "Evan"],
    "Age" : [27 , 24 ,22 , 32],
    "Country" : ['UK' , "Canada"  ,"China" , "USA"],
    "Course" :['Python' , 'Data Structure', 'Machine Learning', 'Web Developer'],
    "Marks" : [85 , 72 ,89 , 76]
    }
stdDF = pd.DataFrame(student)
stdDF

     Name  Age Country            Course  Marks
0   David   27      UK            Python     85
1  Samuel   24  Canada    Data Structure     72
2   Terry   22   China  Machine Learning     89
3    Evan   32     USA     Web Developer     76

In [7]:
# Problem 2: Retrieve the Marks column and assign it to a variable b
b = stdDF[['Marks']]
b

   Marks
0     85
1     72
2     89
3     76

In [10]:
#Problem 3: Retrieve the Country and Course columns and assign it to a variable c¶
c = stdDF[['Country' ,'Course']]
c

  Country            Course
0      UK            Python
1  Canada    Data Structure
2   China  Machine Learning
3     USA     Web Developer

In [16]:
#check the type of a
type(a)

pandas.core.series.Series

In [21]:
mark = stdDF.loc[0, 'Marks']
mark

np.int64(85)

In [23]:
x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'],
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [28]:
df2=df
df2=df2.set_index("Name")
df2

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [29]:
df2.head()

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [30]:
df2.loc['Jane', 'Salary']

np.int64(50000)

In [32]:
df2.loc['Jane', 'Department']

'Design Team'

In [42]:
df2

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [46]:
df2.iloc[3, 2]

np.int64(60000)

In [47]:
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [52]:
df.loc[2:3,'Name':'Department']

   Name  ID      Department
2  Jane   3     Design Team
3  Mary   4  Infrastructure